# 👨🏻‍💻 **Team Notebook — NASA Software Defect Prediction Challenge**
## 🤖 **Machine Learning Challenge** 🤖

---

## **The Challenge**

You receive **software metrics extracted from real NASA mission code**.
Build a classifier that predicts whether a software module contains bugs.

This is a **real industry problem** — companies like NASA, Google and Microsoft
use ML to prioritise code review before releases.

---

## **Your Files**

| File                  | Description                        | Use                   |
|-----------------------|------------------------------------|-----------------------|
| `cm1.csv`             | Scientific instrument (spacecraft) | Training / Validation |
| `pc1.csv`             | Flight software (Earth satellite)  | Training / Validation |
| `jm1.csv`             | Real-time ground system (large)    | Training / Validation |
| `kc1.csv`             | Storage management system          | Training / Validation |
| `kc2_test_blind.csv`  | Secret mission — **no labels**     | Predict & Submit      |

---

## **What You Submit**

A file named **`predictions_TEAMNAME.csv`**:

```
id,defects
0,0
1,1
2,0
```

- `id` — row index (0 to 521)
- `defects` — **1 = buggy**, **0 = clean**

---

## **Scenario Details**

| Training Data             | Test Data   |
|---------------------------|-------------|
| CM1 / PC1 / JM1 / KC1     | KC2         |
| ...                       | ...         |

In [3]:
import pandas as pd
import os

In [4]:
path= r"C:\Users\Usuario\PycharmProjects\nasa-promise\datasets\datasets"
df_cm1_path = os.path.join(path, "cm1.csv")
df_pc1_path = os.path.join(path, "pc1.csv")
df_jm1_path = os.path.join(path, "jm1.csv")
df_kc1_path = os.path.join(path, "kc1.csv")


df_cm1 = pd.read_csv(df_cm1_path)
df_pc1 = pd.read_csv(df_pc1_path)
df_jm1 = pd.read_csv(df_jm1_path)
df_kc1 = pd.read_csv(df_kc1_path)

In [5]:
df_cm1.head()

,loc,v(g),ev(g),iv(g),n,v,l,d,i,e,...,lOCode,lOComment,lOBlank,locCodeAndComment,uniq_Op,uniq_Opnd,total_Op,total_Opnd,branchCount,defects
0,1.1,1.4,1.4,1.4,1.3,1.30,1.30,1.30,1.30,1.30,...,2,2,2,2,1.2,1.2,1.2,1.2,1.4,False
1,1.0,1.0,1.0,1.0,1.0,1.00,1.00,1.00,1.00,1.00,...,1,1,1,1,1.0,1.0,1.0,1.0,1.0,True
2,24.0,5.0,1.0,3.0,63.0,309.13,0.11,9.50,32.54,2936.77,...,1,0,6,0,15.0,15.0,44.0,19.0,9.0,False
3,20.0,4.0,4.0,2.0,47.0,215.49,0.06,16.00,13.47,3447.89,...,0,0,3,0,16.0,8.0,31.0,16.0,7.0,False
4,24.0,6.0,6.0,2.0,72.0,346.13,0.06,17.33,19.97,5999.58,...,0,0,3,0,16.0,12.0,46.0,26.0,11.0,False

In [6]:
df_pc1.head()

,loc,v(g),ev(g),iv(G),N,V,L,D,I,E,...,lOCode,lOComment,locCodeAndComment,lOBlank,uniq_Op,uniq_Opnd,total_Op,total_Opnd,branchCount,defects
0,1.1,1.4,1.4,1.4,1.3,1.30,1.30,1.30,1.30,1.30,...,2,2,2,2,1.2,1.2,1.2,1.2,1.4,False
1,1.0,1.0,1.0,1.0,1.0,1.00,1.00,1.00,1.00,1.00,...,1,1,1,1,1.0,1.0,1.0,1.0,1.0,True
2,91.0,9.0,3.0,2.0,318.0,2089.21,0.04,27.68,75.47,57833.24,...,80,44,11,31,29.0,66.0,192.0,126.0,17.0,True
3,109.0,21.0,5.0,18.0,381.0,2547.56,0.04,28.37,89.79,72282.68,...,97,41,12,24,28.0,75.0,229.0,152.0,38.0,True
4,505.0,106.0,41.0,82.0,2339.0,20696.93,0.01,75.93,272.58,1571506.88,...,457,71,48,49,64.0,397.0,1397.0,942.0,178.0,True

In [7]:
df_cm1.isna().sum()

loc                  0
v(g)                 0
ev(g)                0
iv(g)                0
n                    0
v                    0
l                    0
d                    0
i                    0
e                    0
b                    0
t                    0
lOCode               0
lOComment            0
lOBlank              0
locCodeAndComment    0
uniq_Op              0
uniq_Opnd            0
total_Op             0
total_Opnd           0
branchCount          0
defects              0
dtype: int64

In [8]:
df_pc1.isna().sum()

loc                  0
v(g)                 0
ev(g)                0
iv(G)                0
N                    0
V                    0
L                    0
D                    0
I                    0
E                    0
B                    0
T                    0
lOCode               0
lOComment            0
locCodeAndComment    0
lOBlank              0
uniq_Op              0
uniq_Opnd            0
total_Op             0
total_Opnd           0
branchCount          0
defects              0
dtype: int64

In [9]:
df_jm1.isna().sum()

loc                  0
v(g)                 0
ev(g)                0
iv(g)                0
n                    0
v                    0
l                    0
d                    0
i                    0
e                    0
b                    0
t                    0
lOCode               0
lOComment            0
lOBlank              0
locCodeAndComment    0
uniq_Op              0
uniq_Opnd            0
total_Op             0
total_Opnd           0
branchCount          0
defects              0
dtype: int64

In [10]:
df_kc1.isna().sum()

loc                  0
v(g)                 0
ev(g)                0
iv(g)                0
n                    0
v                    0
l                    0
d                    0
i                    0
e                    0
b                    0
t                    0
lOCode               0
lOComment            0
lOBlank              0
locCodeAndComment    0
uniq_Op              0
uniq_Opnd            0
total_Op             0
total_Opnd           0
branchCount          0
defects              0
dtype: int64